# Generated by Django 4.2.14 on 2025-10-26 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcastgeneration",
            name="source_file",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="citations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="gemini_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="gemini_file_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="gemini_upload_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cache_id", models.CharField(blank=True, max_length=255, null=True)),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                ("cache_token_count", models.IntegerField(default=0)),
                ("files", models.ManyToManyField(blank=True, to="api.uploadedfile")),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContextCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gemini_cache_id", models.CharField(max_length=255, unique=True)),
                ("cache_name", models.CharField(max_length=255)),
                ("token_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.knowledgebase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="api.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="podcastgeneration",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.knowledgebase",
            ),
        ),
    ]
