# Generated by Django 4.2.14 on 2025-10-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_podcastgeneration_source_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="files",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="api.knowledgebase",
            ),
        ),
    ]
