# Generated by Django 4.2.14 on 2025-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_knowledgebase_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="cache_expires_at",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="cache_id",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="cache_token_count",
        ),
        migrations.DeleteModel(
            name="ContextCache",
        ),
    ]
