# Generated by Django 4.2.14 on 2026-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_add_chat_and_filesearch_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="file_search_store_name",
            field=models.CharField(
                blank=True,
                help_text="Gemini File Search store name for this KB",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="mindmap",
            field=models.JSONField(
                blank=True,
                help_text="Latest generated mindmap (MapNode list or dict)",
                null=True,
            ),
        ),
    ]
