# Generated by Django 6.0.2 on 2026-02-16 17:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_knowledgebase_file_search_store_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastgeneration",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.get_podcast_upload_path
            ),
        ),
    ]
