# Generated by Django 6.0.2 on 2026-03-14 08:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_quiz_quizquestion_flashcarddeck_flashcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastgeneration",
            name="audio_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=api.models.get_podcast_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=api.models.get_upload_path
            ),
        ),
    ]
