# Generated by Django 5.2.7 on 2026-04-18 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_podcastgeneration_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='FAQs', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_lists', to='api.knowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The frequently asked question')),
                ('answer', models.TextField(help_text='The detailed answer')),
                ('faq_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.faqlist')),
            ],
        ),
        migrations.DeleteModel(
            name='PodcastGeneration',
        ),
    ]
